credentials:
  system:
    domainCredentials:
      - credentials:
          - string:
              description: "Slack token"
              id: "slack-token"
              scope: GLOBAL
              secret: "${SLACK_TOKEN}"
