unclassified:
  gitHubPluginConfig:
  jiraGlobalConfiguration:
    sites:
      - url: "https://jira-preprod.nuxeo.com/"
  slackNotifier:
    teamDomain: "nuxeo"
    tokenCredentialId: "slack-token"
  timestamper:
    allPipelines: true
