credentials:
  system:
    domainCredentials:
      - credentials:
          - usernamePassword:
              description: "NXBT-2856 JIRA plugin"
              id: "JIRA_PLUGIN"
              scope: GLOBAL
              username: "hudson"
              password: "${JIRA_PASSWORD}"
      - credentials:
          - string:
              description: "NXBT-2856 nuxeojenkins GitHub API token"
              id: "github_token"
              scope: GLOBAL
              secret: "${GITHUB_TOKEN}"
        domain:
          description: "GitHub API domain"
          name: "api.github.com"
      - credentials:
          - string:
              description: "Slack token"
              id: "slack-token"
              scope: GLOBAL
              secret: "${SLACK_TOKEN}"
