groovy:
  - script: >
      import jenkins.model.*;
      import org.csanchez.jenkins.plugins.kubernetes.*;

      if (!Jenkins.instance.clouds) {
          return;
      };
      def kubernetesCloud = Jenkins.instance.clouds.get(0);
      kubernetesCloud.setContainerCap(10000)

      def podLabels = kubernetesCloud.getPodLabels();
      def customLabels = [new PodLabel('team', 'platform'), new PodLabel('resource', 'pod'), new PodLabel('usage', 'build')];
      if (customLabels.disjoint(podLabels)) {
        podLabels.addAll(customLabels);
        kubernetesCloud.setPodLabels(podLabels);
      }
