jenkins:
  authorizationStrategy:
    github:
      adminUserNames: "ataillefer, bdelbosc, kevinleturc, NourNuxeo, troger"
      allowAnonymousJobStatusPermission: false
      allowAnonymousReadPermission: false
      allowCcTrayPermission: false
      allowGithubWebHookPermission: true
      authenticatedUserCreateJobPermission: false
      authenticatedUserReadPermission: false
      organizationNames: "nuxeo"
      useRepositoryPermissions: true
  securityRealm:
    github:
      githubWebUri: "https://github.com"
      githubApiUri: "https://api.github.com"
      clientID: "${GITHUB_ID}"
      clientSecret: "${GITHUB_SECRET}"
      oauthScopes: "read:org,user:email,repo"
