jenkins:
  securityRealm:
    github:
      githubWebUri: "https://github.com"
      githubApiUri: "https://api.github.com"
      clientID: "3bc5c0b47e1804b3b144"
      clientSecret: "${GITHUB_SECRET}"
      oauthScopes: "read:org,user:email,repo"
