jenkins:
  authorizationStrategy:
    github:
      adminUserNames: "admin, ataillefer, atchertchian, bdelbosc, kevinleturc, NourNuxeo, troger"
      allowAnonymousJobStatusPermission: false
      allowAnonymousReadPermission: false
      allowCcTrayPermission: false
      allowGithubWebHookPermission: true
      authenticatedUserCreateJobPermission: false
      authenticatedUserReadPermission: false
      organizationNames: "nuxeo"
      useRepositoryPermissions: true
  securityRealm:
    github:
      githubWebUri: "https://github.com"
      githubApiUri: "https://api.github.com"
      clientID: "${GITHUB_ID}"
      clientSecret: "${GITHUB_SECRET}"
      oauthScopes: "read:org,user:email,repo"
  globalNodeProperties:
    - envVars:
        env:
          - key: "ARENDER_DOCKER_REGISTRY"
            value: "docker-arender.packages.nuxeo.com"
          - key: "ARENDER_HOST_DOCKER_REGISTRY"
            value: "docker-private-arondor-host.packages.nuxeo.com"
          - key: "CONNECT_PROD_SITE_URL"
            value: "https://connect.nuxeo.com/nuxeo/site/"
          - key: "CONNECT_PREPROD_SITE_URL"
            value: "https://nos-preprod-connect.nuxeocloud.com/nuxeo/site/"
          - key: "DOCKER_REGISTRY"
            value: "docker.platform.dev.nuxeo.com"
          - key: "PRIVATE_DOCKER_REGISTRY"
            value: "docker-private.packages.nuxeo.com"
          - key: "PUBLIC_DOCKER_REGISTRY"
            value: "docker.packages.nuxeo.com"
          - key: "YUM_REGISTRY"
            value: "http://nexus.platform/repository/yum-registry/"
