unclassified:
  gitHubPluginConfig:
    configs:
      - credentialsId: "github_token"
        name: "nuxeo"
  jiraGlobalConfiguration:
    sites:
      - credentialsId: "JIRA_PLUGIN"
        readTimeout: 30
        recordScmChanges: false
        supportsWikiStyleComment: true
        threadExecutorNumber: 10
        timeout: 10
        updateJiraIssueForAllStatus: true
        url: "https://jira.nuxeo.com/"
  slackNotifier:
    teamDomain: "nuxeo"
    tokenCredentialId: "slack-token"
  timestamper:
    allPipelines: true
